- name: NGINE CONFIGURATION
  hosts: webservers
  become: true
  vars:
    domain: "{{ lookup('env', 'DOMAIN') }}"
    email: "{{ lookup('env', 'EMAIL') }}"
  tasks:

    - name: Copy nginx template file
      ansible.builtin.template:
        src: ../nginx/packeton.conf.j2
        dest: /etc/nginx/conf.d/packeton.conf
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Generate SSL certificate with Certbot for Nginx
      ansible.builtin.shell: |
        certbot --nginx -d {{ domain }} -m {{ email }} --agree-tos --no-eff-email --redirect
      args:
        creates: /etc/letsencrypt/live/{{ domain }}/fullchain.pem

    - name: Setup cron job for automatic cert renewal
      ansible.builtin.cron:
        name: "Renew Let's Encrypt certificates"
        job: "/usr/bin/certbot renew --quiet"
        state: present
        minute: "0"
        hour: "3"
