- name: Deploy docker-compose
  hosts: all
  become: true
  pre_tasks:
    - name: Set variables in server
      ansible.builtin.set_fact:
        POSTGRES_USER: "{{ lookup('env', 'POSTGRES_USER') }}"
        POSTGRES_PASSWORD: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
        POSTGRES_DB: "{{ lookup('env', 'POSTGRES_DB') }}"
        ADMIN_USER: "{{ lookup('env', 'ADMIN_USER') }}"
        ADMIN_PASSWORD: "{{ lookup('env', 'ADMIN_PASSWORD') }}"
        ADMIN_EMAIL: "{{ lookup('env', 'ADMIN_EMAIL') }}"
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        AWS_REGION: "{{ lookup('env', 'AWS_REGION') }}"
        S3_BUCKET_NAME: "{{ lookup('env', 'S3_BUCKET_NAME') }}"

  tasks:
    - name: Copy docker-compose.yml file
      ansible.builtin.copy:
        src: ../docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
        owner: root
        group: root
        mode: '0644'

    - name: Run docker compose file
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu
        state: present
        build: always
        pull: missing
        recreate: always
        remove_orphans: true
        timeout: 60
        project_name: speardevs_packeton
        files:
          - docker-compose.yml

    - name: Ensure docker-compose is running
      ansible.builtin.systemd:
        name: docker-compose@speardevs_packeton
        state: started
        enabled: true

    - name: Remove docker-compose.yml file
      ansible.builtin.file:
        path: /home/ubuntu/docker-compose.yml
        state: absent

    - name: Copy .env.local file
      community.docker.docker_container_copy_into:
        name: speardevs_packeton_packeton
        path: .env.local
        container_path: /data/.env.local
