- name: Deploy docker-compose
  hosts: all
  become: true

  tasks:
    - name: Create .env file
      ansible.builtin.copy:
        dest: /home/ubuntu/.env
        content: |
          POSTGRES_USER={{ POSTGRES_USER }}
          POSTGRES_PASSWORD={{ POSTGRES_PASSWORD }}
          POSTGRES_DB={{ POSTGRES_DB }}
          ADMIN_USER={{ ADMIN_USER }}
          ADMIN_PASSWORD={{ ADMIN_PASSWORD }}
          ADMIN_EMAIL={{ ADMIN_EMAIL }}
          AWS_ACCESS_KEY_ID={{ AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY={{ AWS_SECRET_ACCESS_KEY }}
          AWS_REGION={{ AWS_REGION }}
          S3_BUCKET_NAME={{ S3_BUCKET_NAME }}
        owner: root
        group: root
        mode: '0644'

    - name: Copy docker-compose.yml file
      ansible.builtin.copy:
        src: ../docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
        owner: root
        group: root
        mode: '0644'

    - name: Run docker compose file
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu
        state: absent
        remove_orphans: true
        remove_volumes: true
        remove_images: all
        timeout: 60
        project_name: speardevs_packeton
        files:
          - docker-compose.yml

    - name: Remove docker-compose.yml file
      ansible.builtin.file:
        path: /home/ubuntu/docker-compose.yml
        state: absent