name: Add packeton user

on:
  workflow_dispatch:
    inputs:
      maintainer:
        type: choice
        description: 'Packeton maintainer'
        required: true
        options:
          - 'Add_user'
          - 'Delete_user'
      username:
        type: string
        description: 'Packeton username'
        required: true
        default: 'username'
      email:
        type: string
        description: 'Packeton email'
        default: ''
      password:
        type: string
        description: 'Packeton password'
        default: ''
      role:
        type: choice
        description: 'Packeton role'
        options:
          - 'ROLE_USER'
          - 'ROLE_FULL_CUSTOMER'
          - 'ROLE_MAINTAINER'
          - 'ROLE_ADMIN'

jobs:
  add-user:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Add user
      if: ${{ github.event.inputs.maintainer == 'Add_user' }}
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.ANSIBLE_SERVER_IP }}
        username: ${{ secrets.ANSIBLE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY_SERVER }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          docker exec -i packeton-packeton /bin/bash -c " \
          bin/console packagist:user:manager ${{ github.event.inputs.username }} \
          --email=${{ github.event.inputs.email }} \
          --password=${{ github.event.inputs.password }} \
          --add-role=${{ github.event.inputs.role }}"

    - name: Delete user
      if: ${{ github.event.inputs.maintainer == 'Delete_user' }}
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.ANSIBLE_SERVER_IP }}
        username: ${{ secrets.ANSIBLE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY_SERVER }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          docker exec -i packeton-packeton /bin/bash -c " \
          bin/console packagist:user:manager ${{ github.event.inputs.username }} \
          --delete"
