name: Ansible Lint

on:
  push:
    paths:
      - 'playbooks/**'

  pull_request:
    paths:
      - 'playbooks/**'
  workflow_dispatch:

jobs:
  ansible-lint:
    name: Lint Ansible Playbooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24.9.2
        with:
          working_directory: playbooks/